apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-traffic-routes

resources:
  - ../base
  - destination-rule.yaml
  - virtual-service.yaml
  - gateway.yaml 
  - namespace.yaml